name: credit_mlops
services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    image: sirsanndy/credit_mlops
    container_name: credit_mlops
    ports:
      - "8000:8000"
    env_file:
      - .env
  ui: 
    build:
        context: .
        dockerfile: ui/Dockerfile
    image: sirsanndy/ui_mlops
    container_name: ui_mlops
    ports:
      - "8051:8051"
    env_file:
      - .env