name: CI
on:
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Create .env File
      run: |
        echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> .env
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> .env
        echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
        echo "MODEL_ALIAS=${{ secrets.MODEL_ALIAS }}" >> .env
        echo "MODEL_SERVER_IP=${{ secrets.MODEL_SERVER_IP_CI }}" >> .env
    - name: Build Container
      run: |
        docker compose up --build -d
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest src/unit_test.py